volumes:
  pg_data:

services:
  db:
    image: postgres:17.6
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ./frontend/
  gateway:
    build: ./gateway/
    ports:
      - 8000:80